Use master branch of Autodesk/revit-ifc to create 2023 version.
bimone/IFC-for-Revit pull request #4
Opened 2022-04-28 18:43 UTC by YannickBolduc

https://github.com/Autodesk/revit-ifc/commit/df1485b9accd598c2912a055af205ee1b03648c7

2022-05-09 14:47 UTC, AlainBolduc commented on 2023/Source/Revit.IFC.Common/Revit.IFC.Common.csproj
> +    <PostBuildEvent>xcopy "$(TargetPath)" "C:\ProgramData\Autodesk\ApplicationPlugins\IFC 2023.bundle\Contents\2023\" /F /R /Y /I</PostBuildEvent>
Devrait pas être hardcodé ici ça

2022-05-09 15:26 UTC, AlainBolduc commented
Aussi, s'assurer que les modifications additionnelles qu'on avait fait à 2022 (https://github.com/bimone/IFC-for-Revit/commits/master/2022/Source) ont été faites pour2023:

- Force x64
- Use PackageReference 
- Do not reference programfiles

2022-05-09 15:29 UTC, AlainBolduc requested changes

2022-05-09 19:56 UTC, YannickBolduc commented on 2023/Source/Revit.IFC.Common/Revit.IFC.Common.csproj
> +    <Reference Include="RevitAPI, Version=23.0.0.0, Culture=neutral, PublicKeyToken=null">
Ok oui, j'ai fait la modification.

2022-05-09 19:57 UTC, YannickBolduc commented on 2023/Source/Revit.IFC.Common/Revit.IFC.Common.csproj
> +    <PostBuildEvent>xcopy "$(TargetPath)" "C:\ProgramData\Autodesk\ApplicationPlugins\IFC 2023.bundle\Contents\2023\" /F /R /Y /I</PostBuildEvent>
ok oui, j'ai enlevé les PostBuildEvent. Je vais ajouter ça dans la doc.

2022-05-10 13:46 UTC, AlainBolduc approved these changes

2022-05-10 19:24 UTC, merged